// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortfolioRebalancer.Api.Data;

#nullable disable

namespace PortfolioRebalancer.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortfolioRebalancer.Api.Domain.Holding", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("PortfolioId").HasColumnType("uuid");
                b.Property<string>("Ticker").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.HasKey("Id");
                b.HasIndex("PortfolioId");
                b.ToTable("Holdings");
            });

            modelBuilder.Entity("PortfolioRebalancer.Api.Domain.Lot", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<decimal>("CostBasisPerShare").HasColumnType("numeric(18,4)");
                b.Property<Guid>("HoldingId").HasColumnType("uuid");
                b.Property<DateOnly>("PurchasedAt").HasColumnType("date");
                b.Property<decimal>("Shares").HasColumnType("numeric(18,6)");
                b.HasKey("Id");
                b.HasIndex("HoldingId");
                b.ToTable("Lots");
            });

            modelBuilder.Entity("PortfolioRebalancer.Api.Domain.Portfolio", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<decimal>("DriftTolerancePct").HasColumnType("numeric(6,4)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("UserId").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Portfolios");
            });

            modelBuilder.Entity("PortfolioRebalancer.Api.Domain.RebalancingEvent", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("PortfolioId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("PortfolioId");
                b.ToTable("RebalancingEvents");
            });

            modelBuilder.Entity("PortfolioRebalancer.Api.Domain.RebalancingOrder", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("Action").IsRequired().HasColumnType("text");
                b.Property<decimal>("EstimatedValue").HasColumnType("numeric(18,2)");
                b.Property<Guid>("EventId").HasColumnType("uuid");
                b.Property<decimal>("Shares").HasColumnType("numeric(18,6)");
                b.Property<string>("Ticker").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.HasKey("Id");
                b.HasIndex("EventId");
                b.ToTable("RebalancingOrders");
            });

            modelBuilder.Entity("PortfolioRebalancer.Api.Domain.TargetAllocation", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("PortfolioId").HasColumnType("uuid");
                b.Property<decimal>("TargetWeight").HasColumnType("numeric(8,6)");
                b.Property<string>("Ticker").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.HasKey("Id");
                b.HasIndex("PortfolioId");
                b.ToTable("TargetAllocation");
            });

            modelBuilder.Entity("PortfolioRebalancer.Api.Domain.Holding", b =>
            {
                b.HasOne("PortfolioRebalancer.Api.Domain.Portfolio", null)
                    .WithMany("Holdings")
                    .HasForeignKey("PortfolioId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("PortfolioRebalancer.Api.Domain.Lot", b =>
            {
                b.HasOne("PortfolioRebalancer.Api.Domain.Holding", null)
                    .WithMany("Lots")
                    .HasForeignKey("HoldingId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("PortfolioRebalancer.Api.Domain.RebalancingEvent", b =>
            {
                b.HasOne("PortfolioRebalancer.Api.Domain.Portfolio", null)
                    .WithMany("RebalancingEvents")
                    .HasForeignKey("PortfolioId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("PortfolioRebalancer.Api.Domain.RebalancingOrder", b =>
            {
                b.HasOne("PortfolioRebalancer.Api.Domain.RebalancingEvent", null)
                    .WithMany("Orders")
                    .HasForeignKey("EventId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("PortfolioRebalancer.Api.Domain.TargetAllocation", b =>
            {
                b.HasOne("PortfolioRebalancer.Api.Domain.Portfolio", null)
                    .WithMany("TargetAllocations")
                    .HasForeignKey("PortfolioId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("PortfolioRebalancer.Api.Domain.Holding", b =>
            {
                b.Navigation("Lots");
            });

            modelBuilder.Entity("PortfolioRebalancer.Api.Domain.Portfolio", b =>
            {
                b.Navigation("Holdings");
                b.Navigation("RebalancingEvents");
                b.Navigation("TargetAllocations");
            });

            modelBuilder.Entity("PortfolioRebalancer.Api.Domain.RebalancingEvent", b =>
            {
                b.Navigation("Orders");
            });
#pragma warning restore 612, 618
        }
    }
}
