apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portfolio-rebalancer.fullname" . }}
  labels:
    {{- include "portfolio-rebalancer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "portfolio-rebalancer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "portfolio-rebalancer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: JWT_SECRET
            - name: ConnectionStrings__Postgres
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: ConnectionStrings__Postgres
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
